version: "3.9"

services:
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "localpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: "rh-postgres"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  adminer:
    image: adminer
    container_name: "rh-adminer"
    ports:
      - 8080:8080